-- AlterTable
ALTER TABLE `trades` ADD COLUMN `hidden` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `status` ENUM('PENDING', 'ACCEPTED', 'CANCELLED', 'COMPLETED', 'TRADE_HOLD') NOT NULL DEFAULT 'PENDING';
